### ISSUE TITLE
Fix the filesystem busy error.

### ISSUE THREAD

**Issue by readmodifywrite** [sapphireos/chromatron#17]

**Comment by readmodifywrite** [comment]
zbox@zbox:~/chromatron/python$ chromatron discover
Discovering...
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/chromatron/chromatron.py", line 774, in scan_func
    device.init_scan()
  File "build/bdist.linux-x86_64/egg/chromatron/chromatron.py", line 311, in init_scan
    self._device.scan(get_all=False)
  File "/usr/local/lib/python2.7/dist-packages/sapphire-1.0.2-py2.7.egg/sapphire/devices/device.py", line 379, in scan
    self.get_firmware_info()
  File "/usr/local/lib/python2.7/dist-packages/sapphire-1.0.2-py2.7.egg/sapphire/devices/device.py", line 599, in get_firmware_info
    data = self.get_file("fwinfo")
  File "/usr/local/lib/python2.7/dist-packages/sapphire-1.0.2-py2.7.egg/sapphire/devices/device.py", line 537, in get_file
    data = self._client.read_file(filename, progress=progress)
  File "build/bdist.linux-x86_64/egg/catbus/client.py", line 480, in read_file
    raise ProtocolErrorException
TypeError: __init__() takes at least 2 arguments (1 given)
