### ISSUE TITLE
Device Unreachable

### ISSUE THREAD

**Issue by coreyward** [sapphireos/chromatron#35]
I have a handful of Chromatron devices, and with all of them I get the same result during discovery on USB: 

```
$ chromatron --host usb discover
Discovering...
Traceback (most recent call last):
  File "/usr/local/bin/chromatron", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/chromatron/chromatron.py", line 2713, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/chromatron/chromatron.py", line 1378, in discover
    group = ctx.invoke(show)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/chromatron/chromatron.py", line 1317, in show
    group = ctx.obj['GROUP']()
  File "/usr/local/lib/python2.7/site-packages/chromatron/chromatron.py", line 989, in get_group
    group = DeviceGroup(*query, host=host)
  File "/usr/local/lib/python2.7/site-packages/chromatron/chromatron.py", line 721, in __init__
    self.scan_devices()
  File "/usr/local/lib/python2.7/site-packages/chromatron/chromatron.py", line 762, in scan_devices
    ct = Chromatron(host=match['host'][0], init_scan=False)
  File "/usr/local/lib/python2.7/site-packages/chromatron/chromatron.py", line 296, in __init__
    self._device = Device(host=host)
  File "/usr/local/lib/python2.7/site-packages/sapphire/devices/device.py", line 322, in __init__
    raise DeviceUnreachableException
sapphire.devices.device.DeviceUnreachableException
```

This is on macOS Mojave with USB drivers installed. I flash Arduinos and other atmega chips over USB fine on this computer, so I don't suspect it's a driver issue. I can connect to the Chromatron board over Wifi, but it won't accept commands. E.g.:

```
$ chromatron keys set wifi_ssid my_ssid_here 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/chromatron/chromatron.py", line 759, in scan_func
    device.init_scan()
  File "/usr/local/lib/python2.7/site-packages/chromatron/chromatron.py", line 310, in init_scan
    self._device.scan(get_all=False)
  File "/usr/local/lib/python2.7/site-packages/sapphire/devices/device.py", line 379, in scan
    self.get_firmware_info()
  File "/usr/local/lib/python2.7/site-packages/sapphire/devices/device.py", line 599, in get_firmware_info
    data = self.get_file("fwinfo")
  File "/usr/local/lib/python2.7/site-packages/sapphire/devices/device.py", line 537, in get_file
    data = self._client.read_file(filename, progress=progress)
  File "/usr/local/lib/python2.7/site-packages/catbus/client.py", line 453, in read_file
    response, host = self._exchange(msg)
  File "/usr/local/lib/python2.7/site-packages/catbus/client.py", line 94, in _exchange
    raise NoResponseFromHost(msg.header.msg_type)
NoResponseFromHost: NoResponseFromHost: 61

0 devices in current group
```

I'm wondering if the software is no longer compatible with the original firmware on the Chromatron's. Any help would be appreciated.

**Comment by coreyward** [comment]
I was able to connect to at least one Chromatron device by swapping out the USB cable I was using. It's plausible that the USB-A to USB Micro cable I had originally been using was power-only. Really wish there was an easy way to determine this.

**Comment by readmodifywrite** [comment]
Ah, that's good to hear!  Sorry for the delay - life is... unpredictable at the moment.

The released software on PyPI and the Github master branch should all be compatible with the firmware that shipped on the boards.  There should be a 1.0.1 update available as well (very minor bug fix).

I've had issues with cables before as well - it is indeed frustrating.  Another thing to watch out for is that the power wires tend to be really thin.  Sometimes Chromatron has trouble getting enough power over longer cables, especially if there are any LEDs plugged in.
